version: '3.1'
services:
  fms-app-test:
    image: ${FULL_IMAGE_NAME}
    environment:
      - DB_URL=${DB_URL}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    depends_on:
      - db-test

  db-test:
    image: postgres:13.4-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: fms_db
