version: '3.1'
services:
  app:
    image: ${FULL_IMAGE_NAME}
    environment:
      - DB_URL=${DB_URL}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DICT_FIXED_RATE=${DICT_FIXED_RATE}
      - DICT_COUNTRY_URL=${DICT_COUNTRY_URL}
      - DICT_CITY_URL=${DICT_CITY_URL}
      - DICT_AIRPORT_URL=${DICT_AIRPORT_URL}
    depends_on:
      - db

  db:
    image: postgres:13.4-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: fms_db
