version: '3.1'
services:
  fms:
    container_name: fms
    build:
      context: .
    environment:
      - DB_URL=${DB_URL}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DICT_FIXED_RATE=${DICT_FIXED_RATE}
      - DICT_COUNTRY_URL=${DICT_COUNTRY_URL}
      - DICT_CITY_URL=${DICT_CITY_URL}
      - DICT_AIRPORT_URL=${DICT_AIRPORT_URL}
    depends_on:
      - db

  db:
    container_name: postgresql_db
    image: postgres:13.4-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: fms_db
    volumes:
      - ./psql_storage:/var/lib/postgresql/data
      - ./psql-init:/docker-entrypoint-initdb.d/

  adminer:
    container_name: adminer_web
    image: adminer:4.8.1
    depends_on:
      - db
    ports:
      - "8080:8080"
