project meta_subscriber {
  database_type: 'PostgreSQL'
  Note: 'Meta subscriber'
}

table country {
  code varchar(3) [pk]
  currency varchar(3)
  name varchar(50)
  en_name varchar(50)
  ru_name varchar(50)
  is_active boolean

  indexes {
    name [name: 'idx_country_name']
    en_name [name: 'idx_country_en_name']
    ru_name [name: 'idx_country_ru_name']
  }
}

table city {
  country_code varchar(3) [ref: > country.code]
  code varchar(3)
  name varchar(50)
  en_name varchar(50)
  ru_name varchar(50)
  is_active boolean

  indexes {
    (country_code, code) [pk]
    name [name: 'idx_city_name']
    en_name [name: 'idx_city_en_name']
    ru_name [name: 'idx_city_ru_name']
  }
}

table airport {
  country_code varchar(3) [ref: > country.code]
  city_code varchar(3) [ref: > city.code]
  code varchar(3)
  name varchar(50)
  en_name varchar(50)
  ru_name varchar(50)
  is_active boolean

  indexes {
    (country_code, city_code, code) [pk]
    name [name: 'idx_airport_name']
    en_name [name: 'idx_airport_en_name']
    ru_name [name: 'idx_airport_ru_name']
  }
}

table user {
  id integer [pk, increment]
  name varchar(50)
  is_active boolean
}

table user_contact_type {
  id integer [pk, increment]
  name varchar(50)
  is_active boolean
}

table user_contact {
  user_id integer [ref: > user.id]
  user_contact_type_id integer [ref: > user_contact_type.id]
  name varchar(50)
  is_active boolean

  indexes {
    (user_id, user_contact_type_id) [pk]
  }
}

table schedule_interval {
  id integer [pk]
  day integer
  hour integer
  minute integer
  is_active boolean
}

table subscribe {
  id integer [pk, increment]
  user_id integer [ref: > user.id]
  schedule_interval_id integer [ref: > schedule_interval.id]
  name varchar(50)
  date_from date
  date_to date
  delta_amount integer
  from_location JSON
  to_location JSON
  is_active boolean
}

table subscribe_details {
  subscribe_id integer [ref: > subscribe.id]
  id integer [not null]
  date date
  from_country varchar(3) [ref: > country.code]
  from_city varchar(3) [ref: > city.code]
  from_airport varchar(3) [ref: > airport.code]
  to_country varchar(3) [ref: > country.code]
  to_city varchar(3) [ref: > city.code]
  to_airport varchar(3) [ref: > airport.code]
  is_active boolean

  indexes {
    (subscribe_id, id) [pk]
  }
}

table subscribe_result {
  subscribe_id integer [ref: > subscribe.id]
  id integer
  result_date datetime
  flight_date date
  flight_price double
  from_country varchar(3) [ref: > country.code]
  from_city varchar(3) [ref: > city.code]
  from_airport varchar(3) [ref: > airport.code]
  to_country varchar(3) [ref: > country.code]
  to_city varchar(3) [ref: > city.code]
  to_airport varchar(3) [ref: > airport.code]
  is_active boolean

  indexes {
    (subscribe_id, id) [pk]
  }
}